AWSTemplateFormatVersion: 2010-09-09

Parameters:

  MainVpcCidrBlock:
    Type: String
  PublicSubnetCidrBlock:
    Type: String
  PrivateSubnetCidrBlock:
    Type: String

Resources:

  #------------------------------
  # base network infrastructure
  #------------------------------

  MainVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Ref: MainVpcCidrBlock
      EnableDnsSupport: false
      EnableDnsHostnames: false
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: vpc-main

  MainInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: main-internet-gateway

  MainInternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: MainVpc
      InternetGatewayId:
        Ref: MainInternetGateway

  #----------------
  # public subnet
  #----------------

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: MainVpc
      CidrBlock:
        Ref: PublicSubnetCidrBlock
      Tags:
      - Key: Name
        Value: public-subnet

  PublicSubnetRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: MainVpc
      Tags:
      - Key: Name
        Value: rt-public

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PublicSubnet
      RouteTableId:
        Ref: PublicSubnetRouteTable

  PublicSubnetInternetGatewayRoute:
    Type: AWS::EC2::Route
    DependsOn: MainInternetGateway
    Properties:
      RouteTableId:
        Ref: PublicSubnetRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: MainInternetGateway

  #----------------
  # private subnet
  #----------------

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: MainVpc
      CidrBlock:
        Ref: PrivateSubnetCidrBlock
      Tags:
      - Key: Name
        Value: private-subnet

  PrivateSubnetRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: MainVpc
      Tags:
      - Key: Name
        Value: rt-private

  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PrivateSubnet
      RouteTableId:
        Ref: PrivateSubnetRouteTable

Outputs:

  MainVpc:
    Value: !Ref MainVpc
    Export:
      Name: !Sub "${AWS::StackName}-MainVpc"
  PublicSubnet:
    Value: !Ref PublicSubnet
    Export:
      Name: !Sub "${AWS::StackName}-PublicSubnet"
  PrivateSubnet:
    Value: !Ref PrivateSubnet
    Export:
      Name: !Sub "${AWS::StackName}-PrivateSubnet"
  MainVpcCidrBlock:
    Value: !Ref MainVpcCidrBlock
    Export:
      Name: !Sub "${AWS::StackName}-MainVpcCidrBlock"
  PublicSubnetCidrBlock:
    Value: !Ref PublicSubnetCidrBlock
    Export:
      Name: !Sub "${AWS::StackName}-PublicSubnetCidrBlock"
  PrivateSubnetCidrBlock:
    Value: !Ref PrivateSubnetCidrBlock
    Export:
      Name: !Sub "${AWS::StackName}-PrivateSubnetCidrBlock"
