AWSTemplateFormatVersion: 2010-09-09
Resources:

  #------------------------------
  # base network infrastructure
  #------------------------------

  MainVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.1.0.0/16
      EnableDnsSupport: false
      EnableDnsHostnames: false
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: vpc-main

  MainInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: main-internet-gateway

  MainInternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: MainVpc
      InternetGatewayId:
        Ref: MainInternetGateway

  #----------------
  # public subnet
  #----------------

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: MainVpc
      CidrBlock: 10.1.1.0/24
      AvailabilityZone: us-east-1a
      Tags:
      - Key: Name
        Value: public-subnet

  PublicSubnetRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: MainVpc
      Tags:
      - Key: Name
        Value: rt-public

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PublicSubnet
      RouteTableId:
        Ref: PublicSubnetRouteTable

  PublicSubnetInternetGatewayRoute:
    Type: AWS::EC2::Route
    DependsOn: MainInternetGateway
    Properties:
      RouteTableId:
        Ref: PublicSubnetRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: MainInternetGateway

  #----------------
  # private subnet
  #----------------

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: MainVpc
      CidrBlock: 10.1.2.0/24
      AvailabilityZone: us-east-1a
      Tags:
      - Key: Name
        Value: private-subnet

  PrivateSubnetRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: MainVpc
      Tags:
      - Key: Name
        Value: rt-private

  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PrivateSubnet
      RouteTableId:
        Ref: PrivateSubnetRouteTable

Outputs:
  MainVpc:
    Value: !Ref MainVpc
    Export:
      Name: !Sub "${AWS::StackName}-MainVpc"
  PublicSubnet:
    Value: !Ref PublicSubnet
    Export:
      Name: !Sub "${AWS::StackName}-PublicSubnet"